d0 <- read.table("csv/yearcut0U.csv", sep=",",header=TRUE)
d1 <- read.table("csv/yearcut1U.csv", sep=",",header=TRUE)
d2 <- read.table("csv/yearcut2U.csv", sep=",",header=TRUE)
d3 <- read.table("csv/yearcut3U.csv", sep=",",header=TRUE)

png("billeder/yearcut0U.png", height = 480, width = 800)
par(las=3, lheight =6, mai=c(2,1,1,1))
barplot(d0$interessante.regioner,beside=TRUE,names=d1$ratios,  cex.axis=1.0, cex.names = 1.4, ylab = "Antal regioner" )
par(las=1)
mtext(1, text = "År", line = 8)
dev.off()

png("billeder/yearcut1U.png", height = 480, width = 800)
par(las=3, lheight =6, mai=c(2,1,1,1))
barplot(d1$interessante.regioner,beside=TRUE,names=d1$ratios, cex.axis=1.0,  cex.names = 1.4, ylab = "Antal regioner"  )
par(las=1)
mtext(1, text = "År", line = 8)
dev.off()

png("billeder/yearcut2U.png", height = 480, width = 800)
par(las=3, lheight =6, mai=c(2,1,1,1))
barplot(d2$interessante.regioner,beside=TRUE,names=d2$ratios, cex.axis=1.0, cex.names = 1.4, ylab = "Antal regioner")
par(las=1)
mtext(1, text = "År", line = 8)
dev.off()

png("billeder/yearcut3U.png", height = 480, width = 800)
par(las=3, lheight =6, mai=c(2,1,1,1))
barplot(d3$interessante.regioner,beside=TRUE,names=d3$ratios, cex.axis=1.0,  cex.names = 1.4, ylab = "Antal regioner")
par(las=1)
mtext(1, text = "År", line = 8)
dev.off()
q()
